language: go

go:
  - "1.x"
  - "1.8"
  - "1.9"
  - "1.10.x"

before_install:
  - go get -t -v ./...

script:
  - go test ./callback -race -coverprofile=coverage.txt -covermode=atomic
  - go test ./install -race -coverprofile=coverage.txt -covermode=atomic
  #- ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)