// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// EnvInterface is an autogenerated mock type for the EnvInterface type
type EnvInterface struct {
	mock.Mock
}

// Getenv provides a mock function with given fields: _a0
func (_m *EnvInterface) Getenv(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
